package snippet

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/jezek/xgb/xproto"
	"github.com/jezek/xgb/xtest"
	"github.com/jezek/xgbutil"
	"github.com/jezek/xgbutil/keybind"
	"gopkg.in/yaml.v3"

	"zen-cap/pkg/capture"
)

type Snippet struct {
	ID      string `json:"id" yaml:"-"`
	Name    string `json:"name" yaml:"name"`
	Content string `json:"content" yaml:"content"`
}

type Manager struct {
	snippets []Snippet
	filePath string
	mu       sync.RWMutex
}

// NewManager creates a new snippet manager and loads existing snippets from file
func NewManager(filePath string) (*Manager, error) {
	mgr := &Manager{
		filePath: filePath,
		snippets: make([]Snippet, 0),
	}

	if err := mgr.loadSnippets(); err != nil {
		// If file doesn't exist, it's not a fatal error
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to load snippets: %w", err)
		}
	}

	// Seed default snippets if the loaded list is empty
	if len(mgr.GetAll()) == 0 {
		_, _ = mgr.Add("Zen-Cap Intro", "Welcome to Zen-Cap! Edit snippets.yaml directly with Shift+Alt+` for instant hot-reload.")
		_, _ = mgr.Add("Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit.")
		_, _ = mgr.Add("Go Signature", "// Generated by Zen-Cap\nfunc main() {\n\t\n}")
	}

	return mgr, nil
}

func (m *Manager) loadSnippets() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if _, err := os.Stat(m.filePath); os.IsNotExist(err) {
		return nil
	}

	data, err := os.ReadFile(m.filePath)
	if err != nil {
		return err
	}

	var loaded []Snippet
	if err := yaml.Unmarshal(data, &loaded); err != nil {
		return err
	}

	// Dynamically assign unique IDs in-memory matching their names
	for i := range loaded {
		loaded[i].ID = loaded[i].Name
	}

	m.snippets = loaded
	return nil
}

func (m *Manager) saveSnippets() error {
	m.mu.RLock()
	data, err := yaml.Marshal(m.snippets)
	m.mu.RUnlock()
	if err != nil {
		return err
	}

	dir := filepath.Dir(m.filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(m.filePath, data, 0644)
}

// GetAll returns a copy of all loaded snippets, auto-reloading from disk to support instant external edits
func (m *Manager) GetAll() []Snippet {
	_ = m.loadSnippets()

	m.mu.RLock()
	defer m.mu.RUnlock()

	res := make([]Snippet, len(m.snippets))
	copy(res, m.snippets)
	return res
}

// Add creates and saves a new snippet
func (m *Manager) Add(name, content string) (Snippet, error) {
	m.mu.Lock()
	snip := Snippet{
		ID:      name,
		Name:    name,
		Content: content,
	}
	m.snippets = append(m.snippets, snip)
	m.mu.Unlock()

	if err := m.saveSnippets(); err != nil {
		return Snippet{}, err
	}

	return snip, nil
}

// Update modifies an existing snippet
func (m *Manager) Update(id, name, content string) (bool, error) {
	m.mu.Lock()
	found := false
	for i, snip := range m.snippets {
		if snip.ID == id {
			m.snippets[i].Name = name
			m.snippets[i].Content = content
			m.snippets[i].ID = name // Sync dynamic ID to new name
			found = true
			break
		}
	}
	m.mu.Unlock()

	if !found {
		return false, nil
	}

	if err := m.saveSnippets(); err != nil {
		return false, err
	}

	return true, nil
}

// Delete removes a snippet by ID
func (m *Manager) Delete(id string) (bool, error) {
	m.mu.Lock()
	idx := -1
	for i, snip := range m.snippets {
		if snip.ID == id {
			idx = i
			break
		}
	}

	if idx != -1 {
		m.snippets = append(m.snippets[:idx], m.snippets[idx+1:]...)
	}
	m.mu.Unlock()

	if idx == -1 {
		return false, nil
	}

	if err := m.saveSnippets(); err != nil {
		return false, err
	}

	return true, nil
}

// Paste copies the snippet content to the clipboard and triggers auto-paste
func (m *Manager) Paste(content string) error {
	if err := capture.CopyTextToClipboard(content); err != nil {
		return fmt.Errorf("failed to copy snippet to clipboard: %w", err)
	}

	// Perform auto-paste synchronously with a small delay for OS clipboard sync before process exits
	time.Sleep(100 * time.Millisecond)

	xu, err := xgbutil.NewConn()
	if err != nil {
		return fmt.Errorf("failed to connect to X server: %w", err)
	}
	defer xu.Conn().Close()

	keybind.Initialize(xu)
	if err := xtest.Init(xu.Conn()); err != nil {
		return fmt.Errorf("failed to initialize xtest extension: %w", err)
	}

	norm := normalizeKeyString("ctrl+v")
	_, keycodes, err := keybind.ParseString(xu, norm)
	if err != nil || len(keycodes) == 0 {
		return fmt.Errorf("failed to parse Paste hotkey: %w", err)
	}

	c := xu.Conn()
	// Press Ctrl
	_, kcs, err := keybind.ParseString(xu, "Control_L")
	var ctrlKC byte
	if err == nil && len(kcs) > 0 {
		ctrlKC = byte(kcs[0])
	} else {
		ctrlKC = 37 // fallback
	}

	xtest.FakeInput(c, xproto.KeyPress, ctrlKC, 0, 0, 0, 0, 0)

	// Press and release V
	vKC := byte(keycodes[0])
	xtest.FakeInput(c, xproto.KeyPress, vKC, 0, 0, 0, 0, 0)
	xtest.FakeInput(c, xproto.KeyRelease, vKC, 0, 0, 0, 0, 0)

	// Release Ctrl
	xtest.FakeInput(c, xproto.KeyRelease, ctrlKC, 0, 0, 0, 0, 0)

	return nil
}

func normalizeKeyString(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "+", "-")
	parts := strings.Split(s, "-")
	for i, part := range parts {
		switch part {
		case "ctrl", "control":
			parts[i] = "control"
		case "alt":
			parts[i] = "mod1"
		case "win", "super":
			parts[i] = "mod4"
		case "shift":
			parts[i] = "shift"
		}
	}
	return strings.Join(parts, "-")
}
