package snippet

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/jezek/xgb/xproto"
	"github.com/jezek/xgb/xtest"
	"github.com/jezek/xgbutil"
	"github.com/jezek/xgbutil/keybind"
	"gopkg.in/yaml.v3"

	"zen-cap/pkg/capture"
)

type Snippet struct {
	ID      string    `json:"id" yaml:"-"`
	Name    string    `json:"name" yaml:"name"`
	Content string    `json:"content" yaml:"content"`
	Smart   smartType `json:"smart,omitempty" yaml:"smart,omitempty"`
	Format  string    `json:"format,omitempty" yaml:"format,omitempty"`
}

type Manager struct {
	snippets []Snippet
	filePath string
	mu       sync.RWMutex
}

// NewManager creates a new snippet manager and loads existing snippets from file
func NewManager(filePath string) (*Manager, error) {
	mgr := &Manager{
		filePath: filePath,
		snippets: make([]Snippet, 0),
	}

	if err := mgr.loadSnippets(); err != nil {
		// If file doesn't exist, it's not a fatal error
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to load snippets: %w", err)
		}
	}

	// Seed default snippets if the loaded list is empty
	if len(mgr.GetAll()) == 0 {
		_, _ = mgr.Add("Zen-Cap Intro", "Welcome to Zen-Cap! Edit snippets.yaml directly with Shift+Alt+` for instant hot-reload.")
		_, _ = mgr.Add("Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit.")
		_, _ = mgr.Add("Go Signature", "// Generated by Zen-Cap\nfunc main() {\n\t\n}")
	}

	return mgr, nil
}

func (m *Manager) loadSnippets() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if _, err := os.Stat(m.filePath); os.IsNotExist(err) {
		return nil
	}

	data, err := os.ReadFile(m.filePath)
	if err != nil {
		return err
	}

	var loaded []Snippet
	if err := yaml.Unmarshal(data, &loaded); err != nil {
		return err
	}

	// Dynamically assign unique IDs in-memory matching their names
	for i := range loaded {
		loaded[i].ID = loaded[i].Name
	}

	m.snippets = loaded
	return nil
}

func (m *Manager) saveSnippets() error {
	m.mu.RLock()
	data, err := yaml.Marshal(m.snippets)
	m.mu.RUnlock()
	if err != nil {
		return err
	}

	dir := filepath.Dir(m.filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(m.filePath, data, 0644)
}

// builtinSmartSnippets are the built-in smart snippets prepended to every list.
var builtinSmartSnippets = []Snippet{
	{
		ID:    "__smart_time__",
		Name:  "⚡ Current Time",
		Smart: SmartTypeTime,
	},
	{
		ID:    "__smart_ip__",
		Name:  "⚡ My IP Address",
		Smart: SmartTypeIP,
	},
}

// GetAll returns a copy of all loaded snippets, auto-reloading from disk to support instant external edits.
// Built-in smart snippets are always prepended.
func (m *Manager) GetAll() []Snippet {
	_ = m.loadSnippets()

	m.mu.RLock()
	defer m.mu.RUnlock()

	res := make([]Snippet, 0, len(builtinSmartSnippets)+len(m.snippets))
	res = append(res, builtinSmartSnippets...)
	res = append(res, m.snippets...)
	return res
}

// Add creates and saves a new snippet
func (m *Manager) Add(name, content string) (Snippet, error) {
	m.mu.Lock()
	snip := Snippet{
		ID:      name,
		Name:    name,
		Content: content,
	}
	m.snippets = append(m.snippets, snip)
	m.mu.Unlock()

	if err := m.saveSnippets(); err != nil {
		return Snippet{}, err
	}

	return snip, nil
}

// Update modifies an existing snippet
func (m *Manager) Update(id, name, content string) (bool, error) {
	m.mu.Lock()
	found := false
	for i, snip := range m.snippets {
		if snip.ID == id {
			m.snippets[i].Name = name
			m.snippets[i].Content = content
			m.snippets[i].ID = name // Sync dynamic ID to new name
			found = true
			break
		}
	}
	m.mu.Unlock()

	if !found {
		return false, nil
	}

	if err := m.saveSnippets(); err != nil {
		return false, err
	}

	return true, nil
}

// Delete removes a snippet by ID
func (m *Manager) Delete(id string) (bool, error) {
	m.mu.Lock()
	idx := -1
	for i, snip := range m.snippets {
		if snip.ID == id {
			idx = i
			break
		}
	}

	if idx != -1 {
		m.snippets = append(m.snippets[:idx], m.snippets[idx+1:]...)
	}
	m.mu.Unlock()

	if idx == -1 {
		return false, nil
	}

	if err := m.saveSnippets(); err != nil {
		return false, err
	}

	return true, nil
}

// Paste handles either copying the snippet content to clipboard and pasting it, or typing it out like a human
func (m *Manager) Paste(content string, mode string) error {
	if mode == "type" {
		xu, err := xgbutil.NewConn()
		if err != nil {
			return fmt.Errorf("failed to connect to X server: %w", err)
		}
		defer xu.Conn().Close()

		keybind.Initialize(xu)
		// Small delay to let the picker window fully unmap/destroy and restore focus
		time.Sleep(200 * time.Millisecond)
		return TypeHumanly(xu, content)
	}

	if err := capture.CopyTextToClipboard(content); err != nil {
		return fmt.Errorf("failed to copy snippet to clipboard: %w", err)
	}

	// Perform auto-paste synchronously with a small delay for OS clipboard sync before process exits
	time.Sleep(100 * time.Millisecond)

	xu, err := xgbutil.NewConn()
	if err != nil {
		return fmt.Errorf("failed to connect to X server: %w", err)
	}
	defer xu.Conn().Close()

	keybind.Initialize(xu)
	if err := xtest.Init(xu.Conn()); err != nil {
		return fmt.Errorf("failed to initialize xtest extension: %w", err)
	}

	norm := normalizeKeyString("ctrl+v")
	_, keycodes, err := keybind.ParseString(xu, norm)
	if err != nil || len(keycodes) == 0 {
		return fmt.Errorf("failed to parse Paste hotkey: %w", err)
	}

	c := xu.Conn()
	// Press Ctrl
	_, kcs, err := keybind.ParseString(xu, "Control_L")
	var ctrlKC byte
	if err == nil && len(kcs) > 0 {
		ctrlKC = byte(kcs[0])
	} else {
		ctrlKC = 37 // fallback
	}

	xtest.FakeInput(c, xproto.KeyPress, ctrlKC, 0, 0, 0, 0, 0)

	// Press and release V
	vKC := byte(keycodes[0])
	xtest.FakeInput(c, xproto.KeyPress, vKC, 0, 0, 0, 0, 0)
	xtest.FakeInput(c, xproto.KeyRelease, vKC, 0, 0, 0, 0, 0)

	// Release Ctrl
	xtest.FakeInput(c, xproto.KeyRelease, ctrlKC, 0, 0, 0, 0, 0)

	return nil
}

func TypeHumanly(xu *xgbutil.XUtil, text string) error {
	c := xu.Conn()
	if err := xtest.Init(c); err != nil {
		return fmt.Errorf("xtest init failed: %w", err)
	}

	keyMap := keybind.KeyMapGet(xu)
	if keyMap == nil {
		return fmt.Errorf("failed to get keyboard mapping")
	}
	setup := xproto.Setup(c)
	minKC := setup.MinKeycode
	maxKC := setup.MaxKeycode
	per := keyMap.KeysymsPerKeycode

	_, shiftKCs, _ := keybind.ParseString(xu, "Shift_L")
	var shiftKC byte = 50
	if len(shiftKCs) > 0 {
		shiftKC = byte(shiftKCs[0])
	}

	// Dynamic lookup for Backspace keycode (keysym 0xff08)
	var backspaceKC byte
	for kc := int(minKC); kc <= int(maxKC); kc++ {
		offset := (kc - int(minKC)) * int(per)
		for ci := 0; ci < int(per); ci++ {
			if keyMap.Keysyms[offset+ci] == 0xff08 {
				backspaceKC = byte(kc)
				break
			}
		}
		if backspaceKC != 0 {
			break
		}
	}
	if backspaceKC == 0 {
		backspaceKC = 22 // fallback for standard US keyboard
	}

	// Local random generator to avoid global seed side effects
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))

	// Typo possibilities
	typoPool := []rune("abcdefghijklmnopqrstuvwxyz")

	for i := 0; i < len(text); i++ {
		r := rune(text[i])

		// Determine keysym to look up
		sym := xproto.Keysym(r)
		if r == '\n' {
			sym = 0xff0d // XK_Return
		} else if r == '\t' {
			sym = 0xff09 // XK_Tab
		}

		// Human typo simulation: 2% chance for alphabetic letters
		if ((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) && rnd.Float64() < 0.02 {
			typoChar := typoPool[rnd.Intn(len(typoPool))]
			if typoChar != r {
				typoSym := xproto.Keysym(typoChar)
				var typoKC, typoCol byte
				typoFound := false
				for kc := int(minKC); kc <= int(maxKC); kc++ {
					offset := (kc - int(minKC)) * int(per)
					for ci := 0; ci < int(per); ci++ {
						if keyMap.Keysyms[offset+ci] == typoSym {
							typoKC = byte(kc)
							typoCol = byte(ci)
							typoFound = true
							break
						}
					}
					if typoFound {
						break
					}
				}

				if typoFound {
					needShift := typoCol%2 == 1
					if needShift {
						xtest.FakeInput(c, xproto.KeyPress, shiftKC, 0, 0, 0, 0, 0)
					}
					xtest.FakeInput(c, xproto.KeyPress, typoKC, 0, 0, 0, 0, 0)
					xtest.FakeInput(c, xproto.KeyRelease, typoKC, 0, 0, 0, 0, 0)
					if needShift {
						xtest.FakeInput(c, xproto.KeyRelease, shiftKC, 0, 0, 0, 0, 0)
					}

					// Realization delay (100 - 200 ms)
					time.Sleep(time.Duration(rnd.Intn(100)+100) * time.Millisecond)

					// Backspace to delete the typo
					xtest.FakeInput(c, xproto.KeyPress, backspaceKC, 0, 0, 0, 0, 0)
					xtest.FakeInput(c, xproto.KeyRelease, backspaceKC, 0, 0, 0, 0, 0)

					// Pause before typing correct character (100 - 200 ms)
					time.Sleep(time.Duration(rnd.Intn(100)+100) * time.Millisecond)
				}
			}
		}

		// Find target keycode
		var targetKC, col byte
		found := false
		for kc := int(minKC); kc <= int(maxKC); kc++ {
			offset := (kc - int(minKC)) * int(per)
			for ci := 0; ci < int(per); ci++ {
				if keyMap.Keysyms[offset+ci] == sym {
					targetKC = byte(kc)
					col = byte(ci)
					found = true
					break
				}
			}
			if found {
				break
			}
		}

		if !found {
			continue
		}

		needShift := col%2 == 1
		if needShift {
			xtest.FakeInput(c, xproto.KeyPress, shiftKC, 0, 0, 0, 0, 0)
		}
		xtest.FakeInput(c, xproto.KeyPress, targetKC, 0, 0, 0, 0, 0)
		xtest.FakeInput(c, xproto.KeyRelease, targetKC, 0, 0, 0, 0, 0)
		if needShift {
			xtest.FakeInput(c, xproto.KeyRelease, shiftKC, 0, 0, 0, 0, 0)
		}

		// Fluid human delay
		delay := rnd.Intn(50) + 35
		if r == ' ' {
			delay += rnd.Intn(50) + 40
		} else if r == '.' || r == ',' || r == '?' || r == '!' || r == ';' || r == ':' {
			delay += rnd.Intn(150) + 150
		} else if r == '\n' {
			delay += rnd.Intn(200) + 250
		}

		time.Sleep(time.Duration(delay) * time.Millisecond)
	}

	return nil
}

func normalizeKeyString(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "+", "-")
	parts := strings.Split(s, "-")
	for i, part := range parts {
		switch part {
		case "ctrl", "control":
			parts[i] = "control"
		case "alt":
			parts[i] = "mod1"
		case "win", "super":
			parts[i] = "mod4"
		case "shift":
			parts[i] = "shift"
		}
	}
	return strings.Join(parts, "-")
}
